# Generated by Django 5.0.1 on 2024-04-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_rename_task_task_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Description',
            field=models.TextField(default=''),
        ),
    ]
